name: FlutterChallenge
description: I'm creating a login flutter

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  path_provider: ^1.6.14
  sqflite: ^1.3.0
  auto_size_text: ^2.1.0 #Dependencia que serve para redimensionar textos automaticamente
  curved_navigation_bar: #Dependencia para criar menus curvos animados
  flutter_launcher_name: ^0.0.1
  bubble_bottom_bar: ^1.2.0
  shared_preferences: ^0.5.10
  intl: ^0.15.7
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_name:
  name: "GQ F-Challenge"

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/logo2.png

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
